# Generated by Django 3.0.8 on 2020-07-13 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='role',
            field=models.CharField(default='stu', max_length=20, verbose_name='角色'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='role',
            field=models.CharField(default='tec', max_length=20, verbose_name='角色'),
        ),
        migrations.AlterField(
            model_name='question',
            name='level',
            field=models.CharField(choices=[('1', 'easy'), ('3', 'difficult'), ('2', 'general')], max_length=10, verbose_name='等级'),
        ),
    ]
